import Character from './class/Character';
import Item from './class/Item';
import Equipment from './class/Equipment';
import Target from './class/Target';
import Spell from './class/Spell';
import Cast from './class/Cast';
import Encounter from './class/Encounter';
declare const _default: {
    sum: (a: number, b: number) => number;
    common: {
        ArmorSubclass: typeof import("./enum/ArmorSubclass").default;
        Buff: typeof import("./enum/Buff").Buff;
        Faction: typeof import("./enum/Faction").default;
        Gender: typeof import("./enum/Gender").default;
        ItemClass: typeof import("./enum/ItemClass").default;
        ItemQuality: typeof import("./enum/ItemQuality").default;
        ItemSlot: typeof import("./enum/ItemSlot").default;
        MagicSchool: typeof import("./enum/MagicSchool").default;
        PlayableClass: typeof import("./enum/PlayableClass").default;
        PlayableRace: typeof import("./enum/PlayableRace").default;
        PowerType: typeof import("./enum/PowerType").default;
        PvPRank: typeof import("./enum/PvPRank").default;
        SortOrder: typeof import("./enum/SortOrder").default;
        TargetType: typeof import("./enum/TargetType").default;
        WeaponSubclass: typeof import("./enum/WeaponSubclass").default;
        ItemSuffixType: typeof import("./enum/ItemSuffixType").default;
        Raid: typeof import("./enum/Raid").default;
        WorldBoss: typeof import("./enum/WorldBoss").default;
        factionFromRace: (race: import("./enum/PlayableRace").default) => import("./enum/Faction").default;
        gearSlotFromText: (text: string) => import("./enum/GearSlot").default;
        gearSlotFromItemSlot: (itemSlot: import("./enum/ItemSlot").default) => import("./enum/GearSlot").default;
        raidFromText: (text: string) => import("./enum/Raid").default;
        raidsFromText: (text: string) => import("./enum/Raid").default[];
        worldBossFromText: (text: string) => import("./enum/WorldBoss").default;
        worldBossesFromText: (text: string) => import("./enum/WorldBoss").default[];
        pvpRankFromText: (text: string) => import("./enum/PvPRank").default;
        playableRaceFromText: (text: string) => import("./enum/PlayableRace").default;
        playableClassFromText: (text: string) => import("./enum/PlayableClass").default;
        playableClassesFromText: (text: string) => import("./enum/PlayableClass").default[];
        itemBaseName: (itemName: string) => string;
        itemBonusTypeFromText: (text: string) => import("./enum/ItemBonusType").default;
        itemSuffixTypeFromText: (itemName: string) => import("./enum/ItemSuffixType").default;
        itemQualityFromText: (text: string) => import("./enum/ItemQuality").default;
        buffFromText: (text: string) => import("./enum/Buff").Buff;
        buffsFromText: (text: string) => import("./enum/Buff").Buff[];
        buffMaskFromText: (text: string) => number;
        buffMaskIncludes: (buffMask: number, buff: import("./enum/Buff").Buff) => boolean;
        globalCooldown: number;
        playerLevelCap: number;
        baseSpellCrit: number;
        baseSpellCritMultiplier: number;
        spellHitCap: number;
        spellCritCap: number;
        defaultSettings: (opts?: {
            playerSpec: import("./enum/PlayableSpec").default;
        } | undefined) => import("./interface/Settings").default;
        calcOptsFromSettings: (s: import("./interface/Settings").default) => import("./interface/CalcOpts").default;
        commonNumberResultFromDefault: () => import("./interface/CommonNumberResult").default;
        commonStringResultFromDefault: () => import("./interface/CommonStringResult").default;
        castDmgValuesFromDefault: () => import("./interface/CastDmgValues").default;
        castDmgObjectFromDefault: () => import("./interface/CastDmgObject").default;
        spellChanceToHit: (playerLevel: number, targetLevel: number, spellHit: number) => number;
        spellChanceToMiss: (playerLevel: number, targetLevel: number, spellHit: number) => number;
        spellChanceToCrit: (playerLevel: number, targetLevel: number, spellHit: number, spellCrit: number) => number;
        spellChanceToNormal: (playerLevel: number, targetLevel: number, spellHit: number, spellCrit: number) => number;
        spellPartialResistAvg: (playerLevel: number, playerSpellPenetration: number, targetLevel: number, targetBaseSpellResistance: number, binarySpell: boolean) => number;
        spellCritBonusMultiplier: (opts?: import("./interface/CalcOpts").default | undefined) => number;
        spellCritMultiplier: (opts?: import("./interface/CalcOpts").default | undefined) => number;
        spellCritFromIntellectDivisor: (playerClass: import("./enum/PlayableClass").default) => number;
        spellDmgMultiplier: (spellName: string, additionalMultipliers: number, opts?: import("./interface/CalcOpts").default | undefined) => import("./interface/CommonNumberResult").default;
        spellDmgBase: (spellName: string, dmg: number, opts?: import("./interface/CalcOpts").default | undefined) => number;
        spellBaseChanceToHit: (playerLevel: number, targetLevel: number) => number;
        playerManaRegen: (playerLevel: number, playerSpirit: number, playerMp5: number, opts?: import("./interface/CalcOpts").default | undefined) => import("./interface/ManaRegen").default;
        targetSpellResistanceFromLevel: (playerLevel: number, targetLevel: number, binarySpell: boolean) => number;
        targetSpellResistance: (playerLevel: number, playerSpellPenetration: number, targetLevel: number, targetBaseSpellResistance: number, binarySpell: boolean) => number;
    };
    utils: {
        isNode: boolean;
        isBrowser: boolean;
        isWebWorker: boolean;
        isMobile: () => boolean;
        isEmpty: (obj: object) => boolean;
        isLetter: (char: string) => boolean;
        cloneObject: (o: any) => any;
        newZeroedArray: (len: number) => any[];
        bitMaskFromArray: (array: number[]) => number;
        bitMaskIncludes: (bitMask: number, value: number) => boolean;
        triangularNumber: (n: number) => number;
        roundedString: (num: number, decimals: number) => string;
        capitalize: (s: string) => string;
        fuzzyTextFromString: (s: string) => string;
        fuzzyIncludes: (haystack: string, needle: string) => boolean;
        encodeURI: (str: string) => string;
        decodeURI: (str: string) => string;
        paramFromURL: (paramName: string, URL?: string | undefined) => string | null;
        sanitizeStringForEnum: (s: string) => string;
        getAllEnumKeys: (enumType: object) => string[];
        getAllEnumValues: (enumType: object) => number[];
        getEnumKeyByEnumValue: (myEnum: any, enumValue: string | number) => string;
        getEnumValueFromFuzzyText: (myEnum: any, fuzzyText: string, exact?: boolean | undefined) => string | number;
        getEnumValuesFromFuzzyText: (myEnum: any, fuzzyText: string) => any[];
        getEnumBitmaskFromFuzzyText: (myEnum: any, fuzzyText: string) => any;
    };
    enchant: {
        fromDefault: () => import("./interface/Enchant").default;
        fromJSON: (enchantJSON?: import("./interface/EnchantJSON").default | undefined) => import("./interface/Enchant").default;
        fromJSONArray: (enchantJSONArray: import("./interface/EnchantJSON").default[]) => import("./interface/Enchant").default[];
    };
    item: {
        fromDefault: () => import("./interface/Item").default;
        fromJSON: (itemJSON?: import("./interface/ItemJSON").default | undefined) => import("./interface/Item").default;
        fromJSONArray: (itemJSONArray: import("./interface/ItemJSON").default[]) => import("./interface/Item").default[];
        fromQuery: (opts: import("./interface/ItemQuery").default) => import("./interface/Item").default[];
        isFromRaid: (location: string) => boolean;
        pvpRankFromText: (text: string) => import("./enum/PvPRank").default;
        bonusFromText: (bonus: string) => import("./interface/ItemBonus").default;
        slotFromItemSlot: (slot: import("./enum/ItemSlot").default) => import("./enum/GearSlot").default;
        qualityFromText: (text: string) => import("./enum/ItemQuality").default;
    };
    itemSuffix: {
        fromText: (id: string, type: string, bonus: string, bonus2?: string | undefined, bonus3?: string | undefined) => import("./interface/ItemSuffix").default;
        fromItemNameAndBonusValue: (itemName: string, bonusValue: number) => import("./interface/ItemSuffix").default | undefined;
        fromItemName: (itemName: string) => import("./interface/ItemSuffix").default[];
    };
    gearSettings: {
        itemId: (gearSettingsObj: import("./interface/GearSettings").default, gearSlot: import("./enum/GearSlot").default) => number;
        setItemId: (gearSettingsObj: import("./interface/GearSettings").default, itemId: number, gearSlot?: import("./enum/GearSlot").default | undefined) => number;
        suffixId: (gearSettingsObj: import("./interface/GearSettings").default, gearSlot: import("./enum/GearSlot").default) => number;
        setSuffixId: (gearSettingsObj: import("./interface/GearSettings").default, itemSuffixId: number, gearSlot?: import("./enum/GearSlot").default | undefined) => number;
        enchantId: (gearSettingsObj: import("./interface/GearSettings").default, gearSlot: import("./enum/GearSlot").default) => number;
        setEnchantId: (gearSettingsObj: import("./interface/GearSettings").default, enchantId: number, gearSlot?: import("./enum/GearSlot").default | undefined) => number;
    };
    spell: {
        fromDefault: () => import("./interface/SpellTrio").default;
    };
    locked: {
        getItemId: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        getEnchantId: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        getItem: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => import("./interface/ItemJSON").default | undefined;
        getEnchant: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => import("./interface/EnchantJSON").default | undefined;
        setItem: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default, value: number) => number;
        setEnchant: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default, value: number) => number;
        lockItem: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default, value: number) => number;
        lockEnchant: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default, value: number) => number;
        unequipItem: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        unequipEnchant: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        unlockItem: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        unlockEnchant: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => number;
        unequipItems: (lockedItems: import("./interface/LockedItems").default | undefined) => number;
        unequipEnchants: (lockedEnchants: import("./interface/LockedEnchants").default | undefined) => number;
        unlockItems: (lockedItems: import("./interface/LockedItems").default | undefined) => number;
        unlockEnchants: (lockedEnchants: import("./interface/LockedEnchants").default) => number;
        itemLocked: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => boolean;
        enchantLocked: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => boolean;
        itemEquipped: (lockedItems: import("./interface/LockedItems").default | undefined, itemSlot: import("./enum/ItemSlot").default) => boolean;
        enchantEquipped: (lockedEnchants: import("./interface/LockedEnchants").default | undefined, itemSlot: import("./enum/ItemSlot").default) => boolean;
    };
    optimal: {
        sortByDPS: (a: import("./interface/EquipmentArray").default, b: import("./interface/EquipmentArray").default) => number;
        itemsForSlot: (settings: import("./interface/Settings").default) => import("./interface/ItemJSON").default[] | undefined;
        enchantsForSlot: (settings: import("./interface/Settings").default) => import("./interface/EnchantJSON").default[] | undefined;
        equipment: (settings: import("./interface/Settings").default) => Equipment;
    };
    query: {
        item: (opts: import("./interface/ItemQuery").default) => import("./interface/ItemJSON").default | undefined;
        items: (opts: import("./interface/ItemQuery").default) => import("./interface/ItemJSON").default[];
        itemSet: (opts: import("./interface/ItemQuery").default) => import("./interface/ItemSetJSON").default | undefined;
        itemSets: (opts: import("./interface/ItemQuery").default) => import("./interface/ItemSetJSON").default[];
        itemSuffixes: (opts: any) => import("./interface/ItemSuffix").default[];
        enchant: (opts: import("./interface/ItemQuery").default) => import("./interface/EnchantJSON").default | undefined;
        enchants: (opts: import("./interface/ItemQuery").default) => import("./interface/EnchantJSON").default[];
        spell: (opts: import("./interface/SpellQuery").default) => import("./interface/SpellJSON").default | undefined;
        spells: (opts: import("./interface/SpellQuery").default) => import("./interface/SpellJSON").default[];
    };
    url: {
        stringToParamin: (str: string, opts?: import("./interface/ParaminOptions").default | undefined) => string;
        paraminToString: (paramin: string, opts?: import("./interface/ParaminOptions").default | undefined) => string;
        lockedFromGearParam: (param: string, opts?: import("./interface/ParaminOptions").default | undefined) => Object;
        gearParamFromLocked: (lockedItems: import("./interface/LockedItems").default, lockedEnchants: import("./interface/LockedEnchants").default | null, opts?: import("./interface/ParaminOptions").default | undefined) => string;
        optionFromURL: (name: string) => any;
        publicURL: (equipment: Equipment) => string;
        defaultSettings: () => import("./interface/Settings").default;
    };
    encounter: {
        defaultSettings: (spec?: import("./enum/PlayableSpec").default | undefined) => import("./interface/Settings").default;
        run: (settings: import("./interface/Settings").default) => import("./interface/Encounter").default;
        run2: (settings: import("./interface/Settings").default) => import("./interface/Encounter").default;
    };
    run: (settings: import("./interface/Settings").default) => import("./interface/Encounter").default;
    run2: (settings: import("./interface/Settings").default) => import("./interface/Encounter").default;
    defaultSettings: import("./interface/Settings").default;
    Character: typeof Character;
    Item: typeof Item;
    Equipment: typeof Equipment;
    Target: typeof Target;
    Spell: typeof Spell;
    Cast: typeof Cast;
    Encounter: typeof Encounter;
};
export default _default;
