import CalcOpts from '../interface/CalcOpts';
import Settings from '../interface/Settings';
import ManaRegen from '../interface/ManaRegen';
import CommonNumberResult from '../interface/CommonNumberResult';
import CommonStringResult from '../interface/CommonStringResult';
import CastDmgObject from '../interface/CastDmgObject';
import CastDmgValues from '../interface/CastDmgValues';
import ItemSuffix from '../interface/ItemSuffix';
import ItemBonus from '../interface/ItemBonus';
import GearSlot from '../enum/GearSlot';
import ItemClass from '../enum/ItemClass';
import ItemQuality from '../enum/ItemQuality';
import ItemSuffixType from '../enum/ItemSuffixType';
import ItemBonusType from '../enum/ItemBonusType';
import ArmorSubclass from '../enum/ArmorSubclass';
import WeaponSubclass from '../enum/WeaponSubclass';
import ItemSlot from '../enum/ItemSlot';
import Raid from '../enum/Raid';
import WorldBoss from '../enum/WorldBoss';
import Buff from '../enum/Buff';
import Faction from '../enum/Faction';
import Gender from '../enum/Gender';
import MagicSchool from '../enum/MagicSchool';
import PlayableClass from '../enum/PlayableClass';
import PlayableRace from '../enum/PlayableRace';
import PlayableSpec from '../enum/PlayableSpec';
import PowerType from '../enum/PowerType';
import PvPRank from '../enum/PvPRank';
import SortOrder from '../enum/SortOrder';
import TargetType from '../enum/TargetType';
declare const _default: {
    ArmorSubclass: typeof ArmorSubclass;
    Buff: typeof Buff;
    Faction: typeof Faction;
    Gender: typeof Gender;
    ItemClass: typeof ItemClass;
    ItemQuality: typeof ItemQuality;
    ItemSlot: typeof ItemSlot;
    MagicSchool: typeof MagicSchool;
    PlayableClass: typeof PlayableClass;
    PlayableRace: typeof PlayableRace;
    PowerType: typeof PowerType;
    PvPRank: typeof PvPRank;
    SortOrder: typeof SortOrder;
    TargetType: typeof TargetType;
    WeaponSubclass: typeof WeaponSubclass;
    ItemSuffixType: typeof ItemSuffixType;
    Raid: typeof Raid;
    WorldBoss: typeof WorldBoss;
    GearSlot: typeof GearSlot;
    factionFromRace: (race: PlayableRace) => Faction;
    gearSlotFromText: (text: string) => GearSlot;
    gearSlotFromItemSlot: (itemSlot: ItemSlot) => GearSlot;
    raidFromText: (text: string) => Raid;
    raidsFromText: (text: string) => Raid[];
    worldBossFromText: (text: string) => WorldBoss;
    worldBossesFromText: (text: string) => WorldBoss[];
    pvpRankFromText: (text: string) => PvPRank;
    playableRaceFromText: (text: string) => PlayableRace;
    playableClassFromText: (text: string) => PlayableClass;
    playableClassesFromText: (text: string) => PlayableClass[];
    itemBaseName: (itemName: string) => string;
    itemNameWowhead: (itemName: string) => string;
    itemBonusFromText: (bonus: string) => ItemBonus;
    itemBonusTypeFromText: (text: string) => ItemBonusType;
    itemSuffixTypeFromText: (itemName: string) => ItemSuffixType;
    itemSuffixFromText: (id: number, type: string, bonusText: string, bonusText2?: string | undefined, bonusText3?: string | undefined) => ItemSuffix;
    itemQualityFromText: (text: string) => ItemQuality;
    buffFromText: (text: string) => Buff;
    buffsFromText: (text: string) => Buff[];
    buffMaskFromText: (text: string) => number;
    buffMaskIncludes: (buffMask: number, buff: Buff) => boolean;
    globalCooldown: number;
    playerLevelCap: number;
    baseSpellCrit: number;
    baseSpellCritMultiplier: number;
    spellHitCap: number;
    spellCritCap: number;
    defaultSettings: (opts?: {
        playerSpec: PlayableSpec;
    } | undefined) => Settings;
    calcOptsFromSettings: (s: Settings) => CalcOpts;
    commonNumberResultFromDefault: () => CommonNumberResult;
    commonStringResultFromDefault: () => CommonStringResult;
    castDmgValuesFromDefault: () => CastDmgValues;
    castDmgObjectFromDefault: () => CastDmgObject;
    spellChanceToHit: (playerLevel: number, targetLevel: number, spellHit: number) => number;
    spellChanceToMiss: (playerLevel: number, targetLevel: number, spellHit: number) => number;
    spellChanceToCrit: (playerLevel: number, targetLevel: number, spellHit: number, spellCrit: number) => number;
    spellChanceToNormal: (playerLevel: number, targetLevel: number, spellHit: number, spellCrit: number) => number;
    spellPartialResistAvg: (playerLevel: number, playerSpellPenetration: number, targetLevel: number, targetBaseSpellResistance: number, binarySpell: boolean) => number;
    spellCritBonusMultiplier: (opts?: CalcOpts | undefined) => number;
    spellCritMultiplier: (opts?: CalcOpts | undefined) => number;
    spellCritFromIntellectDivisor: (playerClass: PlayableClass) => number;
    spellDmgMultiplier: (spellName: string, additionalMultipliers: number, opts?: CalcOpts | undefined) => CommonNumberResult;
    spellDmgBase: (spellName: string, dmg: number, opts?: CalcOpts | undefined) => number;
    spellBaseChanceToHit: (playerLevel: number, targetLevel: number) => number;
    playerManaRegen: (playerLevel: number, playerSpirit: number, playerMp5: number, opts?: CalcOpts | undefined) => ManaRegen;
    targetSpellResistanceFromLevel: (playerLevel: number, targetLevel: number, binarySpell: boolean) => number;
    targetSpellResistance: (playerLevel: number, playerSpellPenetration: number, targetLevel: number, targetBaseSpellResistance: number, binarySpell: boolean) => number;
};
export default _default;
