/**
 * These are all types of 'random enchant' items e.g. some cloak of arcane wrath
 */
declare enum ItemSuffixType {
    Invalid = 0,
    Agility = 1,
    ArcaneResistance = 2,
    ArcaneWrath = 3,
    BeastSlaying = 4,
    Blocking = 5,
    Concentration = 6,
    CriticalStrike = 7,
    Defense = 8,
    Eluding = 9,
    FieryWrath = 10,
    FireResistance = 11,
    FrostResistance = 12,
    FrozenWrath = 13,
    Healing = 14,
    HolyWrath = 15,
    Intellect = 16,
    Marksmanship = 17,
    NatureResistance = 18,
    NaturesWrath = 19,
    Power = 20,
    Proficiency = 21,
    Quality = 22,
    Regeneration = 23,
    Restoration = 24,
    Retaliation = 25,
    ShadowResistance = 26,
    ShadowWrath = 27,
    Sorcery = 28,
    Spirit = 29,
    Stamina = 30,
    Strength = 31,
    Striking = 32,
    TheBear = 33,
    TheBoar = 34,
    TheEagle = 35,
    TheFalcon = 36,
    TheGorilla = 37,
    TheMonkey = 38,
    TheOwl = 39,
    TheTiger = 40,
    TheWhale = 41,
    TheWolf = 42,
    Toughness = 43,
    Twain = 44
}
export default ItemSuffixType;
