import Raid from '../enum/Raid';
import WorldBoss from '../enum/WorldBoss';
import ArmorSubclass from '../enum/ArmorSubclass';
import Buffs from '../enum/Buffs';
import Faction from '../enum/Faction';
import Gender from '../enum/Gender';
import ItemClass from '../enum/ItemClass';
import ItemQuality from '../enum/ItemQuality';
import ItemSlot from '../enum/ItemSlot';
import MagicSchool from '../enum/MagicSchool';
import PlayableClass from '../enum/PlayableClass';
import PlayableRace from '../enum/PlayableRace';
import PowerType from '../enum/PowerType';
import PvPRank from '../enum/PvPRank';
import SortOrder from '../enum/SortOrder';
import SpellCritFromIntellectDivisor from '../enum/SpellCritFromIntellectDivisor';
import TargetType from '../enum/TargetType';
import WeaponSubclass from '../enum/WeaponSubclass';
import ItemSuffixType from '../enum/ItemSuffixType';
import ItemBonusType from '../enum/ItemBonusType';
import GearSlot from '../enum/GearSlot';
declare const _default: {
    ArmorSubclass: typeof ArmorSubclass;
    Buffs: typeof Buffs;
    Faction: typeof Faction;
    Gender: typeof Gender;
    ItemClass: typeof ItemClass;
    ItemQuality: typeof ItemQuality;
    ItemSlot: typeof ItemSlot;
    MagicSchool: typeof MagicSchool;
    PlayableClass: typeof PlayableClass;
    PlayableRace: typeof PlayableRace;
    PowerType: typeof PowerType;
    PvPRank: typeof PvPRank;
    SortOrder: typeof SortOrder;
    SpellCritFromIntellectDivisor: typeof SpellCritFromIntellectDivisor;
    TargetType: typeof TargetType;
    WeaponSubclass: typeof WeaponSubclass;
    ItemSuffixType: typeof ItemSuffixType;
    Raid: typeof Raid;
    WorldBoss: typeof WorldBoss;
    factionFromRace: (race: PlayableRace) => Faction;
    buffListToFlags: (buffList: string[]) => Buffs;
    gearSlotFromText: (text: string) => GearSlot;
    raidFromText: (text: string) => Raid;
    raidsFromText: (text: string) => Raid[];
    worldBossFromText: (text: string) => WorldBoss;
    worldBossesFromText: (text: string) => WorldBoss[];
    pvpRankFromText: (text: string) => PvPRank;
    playableRaceFromText: (text: string) => PlayableRace;
    playableClassFromText: (text: string) => PlayableClass;
    playableClassesFromText: (text: string) => PlayableClass[];
    itemBonusTypeFromText: (text: string) => ItemBonusType;
    itemSuffixTypeFromText: (text: string) => ItemSuffixType;
    itemQualityFromText: (text: string) => ItemQuality;
};
export default _default;
